version: '3'
services:
  product_api:
    container_name: product_api
    build: ./productapi
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 && alembic upgrade head
    ports:
      - 8001:8000
    env_file:
      ./.env
    depends_on:
      - product_db
    networks:
      - bound
  product_db:
    image: postgres
    container_name: product_db
    expose:
      - 5432
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - bound
volumes:
  postgres:
networks:
  bound:
    driver: bridge

